### ISSUE TITLE
Maven dependency

### ISSUE THREAD

**Issue by mattiaslundmark** [navikt/boot-cluster-conditionals#10]
Hei,

Jobber på team permittering i PO Arbeidsgiver og fastnet litt på mvn dependency av denne. Denne finnes ikke i åpent maven-repo, og vet ikke helt hvor jeg skal finne den i lukket repo. Men da koden uansett er open source, og jar/pom-filer kan lastes ned direkte fra github, er det da ikke enklest å flytte dependency til åpent maven-repository?

mattias

**Comment by jan-olaveide** [comment]
Bygger ikke dere på github ?

**Comment by jan-olaveide** [comment]
Github package repo er i prinsippet "åpent" for alle med tilgang til navikt-organisasjonen. Riktignok må du inn med et token når du definerer repoet i f.eks settings.xml, men et slik token er automagisk tilgjengelig i alle pipelines.

**Comment by mattiaslundmark** [comment]
Ja, vi bygget med actions, men tenkte egentlig mest på forenkling av localhost. Men løser det enkelt ved å bygge dette lokalt inn i repo. Lukker denne.
